version: "3.1"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    networks:
      - pg-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8081:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
